-- V11.5 · Recepción de mercancía como dominio independiente de bodega
-- La migración completa fue aplicada a Supabase con el nombre warehouse_receiving_domain_v11_5.
-- Esta marca de repositorio documenta la intención de dominio; el historial canónico y SQL aplicado
-- se conserva en supabase_migrations.schema_migrations del proyecto hezjxcxxcjlpmyalftam.
--
-- Contrato funcional:
-- 1. warehouse_receipts / warehouse_receipt_lines son independientes del workflow de pedidos.
-- 2. linked_pve_id y linked_purchase_order_id son opcionales.
-- 3. Solo cantidades aceptadas crean lotes/movimientos de inventario.
-- 4. Si existe linked_pve_id, la recepción marca purchase_arrival_state=ARRIVED (Mercancía OK).
-- 5. Ninguna recepción de mercancía cambia etapa, estado, responsable o ruta del pedido.
